framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            message.bus:
                default_middleware: allow_no_handlers

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # отсюда только беру сообщения
            external_messages:
                dsn: '%env(EXTERNAL_MESSAGE_TRANSPORT_DSN)%'
                serializer: App\Shared\Infrastructure\Serializer\ExternalMessageSerializer
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                options:
                    exchange:
                        name: 'orders'
                        type: topic
                    queues:
                        orders_general:
                            binding_keys: [ '#' ]
                    auto_setup: false
        # https://symfony.com/doc/current/messenger.html#transport-configuration
        # async: '%env(MESSENGER_TRANSPORT_DSN)%'
        # failed: 'doctrine://default?queue_name=failed'
        # sync: 'sync://'

        routing:
            'App\Shared\Domain\Message\ExternalMessage': external_messages
        # Route your messages to the transports
        # 'App\Message\YourMessage': async
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
